export const events = [
  {
    name: "Memory Test",
    date: "March 11",
    time: "3:00 PM",
    duration: "1 hour",
    venue: "Open Air Theater",
    members: "Individual",
    rules: ["Should write in Pencil"],
    eventCoordinator: ["Abhishek G S Sir", "(Dept. of Political Science)", "73532 00495"],
    image: "https://ik.imagekit.io/6b0su29zd/event%20images/memoryTest2.png?updatedAt=1741547055979",
    link: "https://forms.gle/BFFKBYumNKCi4gse9",
  },
  {
    name: "Rangoli",
    date: "March 12",
    time: "3:30 PM",
    duration: "1 hour",
    venue: "Campus-wide",
    members: "Individual",
    rules: ["ಚುಕ್ಕೆ ರಂಗೋಲಿ ಮಾತ್ರ"],
    eventCoordinator: ["Roopa M Madam", "(Dept. of History)", "97431 14147"],
    image: "https://ik.imagekit.io/6b0su29zd/event%20images/rangoli2.jpg?updatedAt=1741546921748",
    link: "https://forms.gle/z1FPc8mq4fkNEJYn6",
  },
  {
    name: "Handwriting Competition",
    date: "March 13",
    time: "2:00 PM",
    duration: "1/2 Hour",
    venue: "Tech Center",
    members: "Individual",
    rules: ["Languages :- Kannda, Engish,Hindi"],
    eventCoordinator: ["Manoj H M Sir", "(Dept. of Computer Science)", "82170 93858"],
    image: "https://ik.imagekit.io/6b0su29zd/event%20images/handwritting.jpg?updatedAt=1741546921751",
    link: "https://forms.gle/p2DbhV71fFKFE5zi6",
  },
  {
    name: "Remix Film Competition",
    date: "March 14",
    time: "2:00 PM",
    duration: "3+1 Minutes",
    venue: "Food Court",
    members: "Minimum 8 , Maximum 10+2",
    rules: ["Can sing in any Language.", "Karaoke can be used.", "Any numbers of teams from a section can participate"],
    eventCoordinator: ["Diana A D'berta Madam", "(Dept. of English)", "89712 74520 "],
    image: "https://ik.imagekit.io/6b0su29zd/event%20images/singing.jpg?updatedAt=1741546922090",
    link: "https://forms.gle/y9NaRgtY43Y3ZDrbA",
  },
  {
    name: "Painting & Drawing",
    date: "March 18",
    time: "3:00 PM",
    duration: "1 hr",
    venue: "Main Auditorium",
    members: "Individual",
    rules: ["ಮಲೆನಾಡಿನ ಹೆಬ್ಬಾಗಿಲು ಶಿವಮೊಗ್ಗ ", "ಚಿತ್ರಕಲೆಗೆ ಸಂಬಂಧಿಸಿದ ಸಾಮಾಗ್ರಿಗಳನ್ನು ವಿದ್ಯಾರ್ಥಿಗಳೇ ತರತಕ್ಕದ್ದು"],
    eventCoordinator: ["Dr Arun Kumar G Sir", "(Dept. of Chemistry)", "90087 91305 "],
    image: "https://ik.imagekit.io/6b0su29zd/event%20images/drawing2.jpg?updatedAt=1741546922096",
    link: "https://forms.gle/8ke3tYEvm62VVoXQ8",
  },
  {
    name: "Quiz",
    date: "March 21-22",
    time: "2:00 PM",
    duration: "Not Specific Time",
    venue: "Digital Media Lab",
    members: "Per Team - 2 Members",
    rules: ["Any number of teams from a section can participate ", "Preliminary round will be written test ", "Top 6 teams will be qualified Topics-General Knowledge"],
    eventCoordinator: ["Samhitha Mahima Bharghav Madam ", "(Dept. of Chemistry)", "99801 73521"],
    image: "https://ik.imagekit.io/6b0su29zd/event%20images/quizz2.png?updatedAt=1741547864676",
    link: "https://forms.gle/mYmHkN21RNvgyrsCA",
  },
  {
    name: "Cooking Without Fire",
    date: "March 22",
    time: "2:00 PM",
    duration: "1 hours",
    venue: "Main Auditorium",
    members: "Per Team - 4 Members",
    rules: ["Bun,Bread and Biscuits are not allowed","Only one food item permitted"],
    eventCoordinator: ["Vaishnavi R Madam", "(Dept. of Computer Science)", "96207 96064"],
    image: "https://ik.imagekit.io/6b0su29zd/event%20images/cookingWithOutFire.png?updatedAt=1741547345394",
    link: "https://forms.gle/QdqQLyrL4WeayP5j7",
  },
  {
    name: "Treasure Hunt",
    date: "March 28-29",
    time: "2:00 PM",
    duration: " 2 Days, Day 1: Primary Round and Day 2:Final Round",
    venue: "Conference Hall",
    members: "Per Team - 4 Members",
    rules: ["Captain of the team only can participate", "Top 6 Teams will be selected"],
    eventCoordinator: ["Anirudh S Sir", "(Dept. of Mathematics)", "70199 03051"],
    image: "https://ik.imagekit.io/6b0su29zd/event%20images/tresureHunt.jpeg?updatedAt=1741546922094",
    link: "https://forms.gle/4LrJUaVegL3XXyJU6",
  },
  {
    name: "Fashion Show",
    date: "March 29",
    time: "1:00 PM",
    duration: "5+1 Minutes",
    venue: "Art Gallery",
    members: "Per Team - 12+1 Members",
    rules: ["ಕರ್ನಾಟಕದ ಹಳ್ಳಿಯ ಸೊಗಡನ್ನು ಪ್ರದರ್ಶಿಸುವುದು."],
    eventCoordinator: ["Pruthvi K J Sir", "(Dept. of Zoology)", "96203 36228"],
    image: "https://ik.imagekit.io/6b0su29zd/event%20images/fashion%20show.jpg?updatedAt=1741546921745",
    link: "https://forms.gle/oZHURAK5QbMhzQkU8",
  },
  {
    name: "Mehndi",
    date: "Date will be announced soon",
    time: "3:30 PM",
    duration: "1 Hour",
    venue: "Main Stage",
    members: "Individual",
    rules: ["Only natural henna allowed", "No pre-drawn designs"],
    eventCoordinator: ["Dr. Rajeshwari N Madam", "Dept. of Kannada", "99868 79716 "],
    image: "https://ik.imagekit.io/6b0su29zd/event%20images/mehendi.png?updatedAt=1741546920951",
    link: "https://forms.gle/8KvLUaGrXdzzxZCa8",
  }
];