export const events = [
    {
      name: "Drawing",
      date: "March 11-12",
      time: "2:00 PM - 6:00 PM",
      venue: "Main Auditorium",
      members: "Individual",
      image: "https://ik.imagekit.io/6b0su29zd/event%20images/drawing2.jpg?updatedAt=1741546922096",
      link: "/register/drawing",
    },
    {
      name: "Fashion Show",
      date: "March 13-14",
      time: "10:00 AM - 5:00 PM",
      venue: "Art Gallery",
      members: "Solo or Group (max 6)",
      image: "https://ik.imagekit.io/6b0su29zd/event%20images/fashion%20show.jpg?updatedAt=1741546921745",
      link: "/register/fashion-show",
    },
    {
      name: "Memory Test",
      date: "March 15",
      time: "4:00 PM - 8:00 PM",
      venue: "Open Air Theater",
      members: "Individual",
      image: "https://ik.imagekit.io/6b0su29zd/event%20images/memoryTest2.png?updatedAt=1741547055979",
      link: "/register/memory-test",
    },
    {
      name: "Treasure Hunt",
      date: "March 16",
      time: "1:00 PM - 5:00 PM",
      venue: "Conference Hall",
      members: "Team (max 4)",
      image: "https://ik.imagekit.io/6b0su29zd/event%20images/tresureHunt.jpeg?updatedAt=1741546922094",
      link: "/register/treasure-hunt",
    },
    {
      name: "Mehndi",
      date: "March 17-18",
      time: "3:00 PM - 7:00 PM",
      venue: "Main Stage",
      members: "Individual",
      image: "https://ik.imagekit.io/6b0su29zd/event%20images/mehendi.png?updatedAt=1741546920951",
      link: "/register/mehndi",
    },
    {
      name: "Rangoli",
      date: "March 19",
      time: "All Day",
      venue: "Campus-wide",
      members: "Solo or Team (max 3)",
      image: "https://ik.imagekit.io/6b0su29zd/event%20images/rangoli2.jpg?updatedAt=1741546921748",
      link: "/register/rangoli",
    },
    {
      name: "Quiz",
      date: "March 20",
      time: "12:00 PM - 4:00 PM",
      venue: "Digital Media Lab",
      members: "Team (max 5)",
      image: "https://ik.imagekit.io/6b0su29zd/event%20images/quizz2.png?updatedAt=1741547864676",
      link: "/register/quiz",
    },
    {
      name: "Cooking Without Fire",
      date: "March 21",
      time: "5:00 PM - 9:00 PM",
      venue: "Main Auditorium",
      members: "Solo or Team (max 2)",
      image: "https://ik.imagekit.io/6b0su29zd/event%20images/cookingWithOutFire.png?updatedAt=1741547345394",
      link: "/register/cooking-without-fire",
    },
    {
      name: "Handwriting",
      date: "March 20-21",
      time: "10:00 AM - 6:00 PM",
      venue: "Tech Center",
      members: "Individual",
      image: "https://ik.imagekit.io/6b0su29zd/event%20images/handwritting.jpg?updatedAt=1741546921751",
      link: "/register/handwriting",
    },
    {
      name: "Remix Film Songs",
      date: "March 22",
      time: "11:00 AM - 3:00 PM",
      venue: "Food Court",
      members: "Solo or Group (max 4)",
      image: "https://ik.imagekit.io/6b0su29zd/event%20images/singing.jpg?updatedAt=1741546922090",
      link: "/register/remix-film-songs",
    },
];